name: Publish Python Distributions to PyPi and TestPyPI

on:
    push:

jobs:
    python-build-npublish:
        name: build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ruff

            - name: Lint with ruff
              run: |
                ruff check .
            
            - name: Build binary wheel and a source tarball
              run: python3 setup.py sdist
              

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with: 
                password: ${{secrets.test_pypi_password}}
                repository_url: https://upload.pypi.org/legacy/
            
            
